// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: HF-OLED-demo2

#ifndef _HF_ENCODER_BUTTO_H
#define _HF_ENCODER_BUTTO_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdio.h>

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/gpio.h"
#include "driver/i2c.h"
#include "driver/spi_master.h"
#include "esp_timer.h"
#include "esp_lcd_panel_io.h"
#include "esp_lcd_panel_vendor.h"
#include "esp_lcd_panel_ops.h"
#include "esp_err.h"
#include "esp_log.h"

#include "lvgl.h"
#include "lv_demos.h"

 extern void encoder_read(lv_indev_drv_t *indev_drv, lv_indev_data_t *data);
 extern   esp_err_t lvgl_port_tick_init(void);
// extern  esp_err_t lvgl_port_indev_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
