// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: HF-ESP-10-7-OLED

#include "ui.h"
#include "lvgl.h"
#include "ui_helpers.h"
#include "esp_log.h"
///////////////////// VARIABLES ////////////////////
static const char *TAG = "ui";
extern  int selected_index;
extern  char * options[];
extern  char * options2[];
extern int options_max_num;
extern int HF_number;
///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
void ui_event_background(lv_event_t * e);
lv_obj_t * ui_background;
lv_obj_t * ui_Image12;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;


// SCREEN: ui_working
void ui_working_screen_init(void);
lv_obj_t * ui_working;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Bar2;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Spinner3;


// SCREEN: ui_time
void ui_time_screen_init(void);
lv_obj_t * ui_time;
lv_obj_t * ui_Roller1;
lv_obj_t * ui_Image1;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Image6;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_back[1] = {&ui_img_back111_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
static uint8_t index2=0;
//******************* */
extern volatile int HF_botton;
extern volatile int HF_botton_time;
extern volatile int HF_encoder_num;
volatile static int num=1;
volatile static int HF_index=1;
uint8_t HF_ui_screen_id=1;//当前屏幕索引  1主界面  2设置时间  3工作
 void my_timer1(lv_timer_t * timer)
{
    //int *user_data = lv_timer_get_user_data(timer);
    
   
    //方法2
    if(HF_botton_time>50)
    {
         if(HF_ui_screen_id==1)
        {
            HF_ui_screen_id=2;
            
             HF_botton=-1;
             HF_index=0;
            _ui_screen_change(&ui_time, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_time_screen_init);
        }

    }
     if(HF_botton==2)//按下抬起
     {
        HF_botton=0;
         HF_index=1;
       
        if(HF_ui_screen_id==1)
        {
            HF_ui_screen_id=3;
            _ui_screen_change(&ui_working, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_working_screen_init);
        }
       else if(HF_ui_screen_id==2)
        {
              
            selected_index = lv_roller_get_selected(ui_Roller1); // 获取当前选中的索引  
            ESP_LOGE(TAG, "ui_Roller1 ==%d",selected_index);
            _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, options[selected_index]);
            HF_ui_screen_id=1;
            _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_Screen1_screen_init);

        }
        else if(HF_ui_screen_id==3)
        {
            HF_ui_screen_id=1;
            _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_Screen1_screen_init);
        }
       
      

     }
     if(HF_encoder_num==1) {//右
       
        HF_encoder_num=0;
        HF_index=1;
     if(HF_ui_screen_id==1)
       {
       index2++;
       if(index2>=7)//只有6张图片
       index2=1;
       }
        else if(HF_ui_screen_id==2)
       {
            selected_index++;
            if(selected_index>options_max_num)
                 selected_index=0;
            lv_roller_set_selected(ui_Roller1,selected_index,LV_ANIM_ON);//旋钮带动滑轮转动
        }
    }
    else if(HF_encoder_num==-1)//左
    {
         HF_encoder_num=0;
         HF_index=1;
        if(HF_ui_screen_id==1)
        {
        index2--;
        if(index2<=0)
        index2=6;
        }
         else if(HF_ui_screen_id==2)
       {
            selected_index--;
            if(selected_index<0)
                 selected_index=options_max_num;
            lv_roller_set_selected(ui_Roller1,selected_index,LV_ANIM_ON);//旋钮带动滑轮转动
        }
    }
    if(HF_index==1)
    {

        HF_index=0;

        
        if(index2==1)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_2kaoji_png);
        else if(index2==2)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_3danta_png);
        else if(index2==3)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_4pisa_png);
        else if(index2==4)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_5liupai_png);
        else if(index2==5)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_6shutiao_png);
        else if(index2==6)
        {
           
            _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_1kaorou_png);
        }
       
   
    }
   
}
///////////////////// FUNCTIONS ////////////////////
void ui_event_background(lv_event_t * e)
{  

{
    //  //方法一
    //  lv_event_code_t code = lv_event_get_code(e);

    // if (LV_EVENT_FOCUSED == code) {
    //     lv_group_set_editing(lv_group_get_default(), true);
    // } else if (LV_EVENT_KEY == code) {
    //     uint32_t key = lv_event_get_key(e);
    //     if (1) {
    //         if (LV_KEY_RIGHT == key) {
    //              ESP_LOGI(TAG, "uichangge T");   旋钮能打印，但是切换不了图片，老问题，还是得用定时器
    //                 index2++;
    //                 if(index2>=7)
    //                 index2=1;
                
    //         } else if (LV_KEY_LEFT == key) {
    //              ESP_LOGI(TAG, "uichangge R");
    //                 index2--;
    //                 if(index2<=0)
    //                 index2=6;
               
    //         }
    //     if(index2==1)
    //     _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_2kaoji_png);
    //     else if(index2==2)
    //     _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_3danta_png);
    //     else if(index2==3)
    //     _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_4pisa_png);
    //     else if(index2==4)
    //     _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_5liupai_png);
    //     else if(index2==5)
    //     _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_6shutiao_png);
    //     else if(index2==6)
    //     {
           
    //         _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_1kaorou_png);
    //     }
    // } 
    // else if (LV_EVENT_CLICKED == code) {
      
    // } else if (LV_EVENT_LONG_PRESSED == code) {
    //     // lv_indev_wait_release(lv_indev_get_next(NULL));
    //     // ui_remove_all_objs_from_encoder_group();
    //     // lv_func_goto_layer(&menu_layer);
    // }
    // }
}
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {//滑动效果依然没有
        lv_indev_wait_release(lv_indev_get_act());
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_2kaoji_png);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_3danta_png);
    }



    if(event_code == LV_EVENT_CLICKED) {//触摸点击
        index2++;
        if(index2>=7)
            index2=1;
        if(index2==1)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_2kaoji_png);
        else if(index2==2)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_3danta_png);
        else if(index2==3)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_4pisa_png);
        else if(index2==4)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_5liupai_png);
        else if(index2==5)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_6shutiao_png);
        else if(index2==6)
        {
           
            _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_1kaorou_png);
        }
    }
    
}
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        HF_ui_screen_id=2;
        _ui_screen_change(&ui_time, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_time_screen_init);
    }
}
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        HF_ui_screen_id=3;
        _ui_screen_change(&ui_working, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_working_screen_init);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        HF_ui_screen_id=1;
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        HF_ui_screen_id=1;
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
         selected_index = lv_roller_get_selected(ui_Roller1); // 获取当前选中的索引  
         HF_number= options2[selected_index];
        ESP_LOGE(TAG, "ui_Roller1 ==%d",selected_index);
        _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, options[selected_index]);
        HF_ui_screen_id=1;
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_Screen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_working_screen_init();
    ui_time_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
